const mongoose = require('mongoose');
const {
    DB_URL,
    CONFIG_DB
} = require('../config/db');
const SneakersModel = require('../models/Sneakers');

const sneakersProductsArray = [
    {
        "title": "Nike Dunk High Retro",
        "description": "El icono del baloncesto de los 80, creado para la cancha y adaptado al estilo urbano.",
        "price": 109.99,
        "stock": 10,
        "shoppingFrom": "España",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/22821215-b39b-4517-b5de-05527dcdc4ce/dunk-high-retro-zapatillas-dlXbK3.png",
        "rating": 4.9,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "Nike Air Force 1 '07 LV8",
        "description": "Con un diseño que combina la diversión retro con el icónico estilo de baloncesto, las Nike Air Force 1 '07 LV8 ofrecen un nuevo giro en lo que mejor conoces.",
        "price": 119.99,
        "stock": 15,
        "shoppingFrom": "Francia",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/7276b8ce-67a4-45fd-8e19-ed6bb0f7772b/air-force-1-07-lv8-zapatillas-4hl24v.png",
        "rating": 4.2,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "Forum Low ",
        "description": " Esta versión luce un diseño con los colores clásicos que podría lucir cualquier equipo en la cancha y que nos recuerda que no estaríamos donde estamos sin la ayuda de los demás.",
        "stock": 33,
        "price": 120,
        "shoppingFrom": "Alemania",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/75aee7eb0fc343d484c9adf30019d225_9366/Zapatilla_Forum_Low_Blanco_GY8556_01_standard.jpg",
        "rating": 3.1,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Adidas",
    },
    {
        "title": "Adidas NMD_R1 V2",
        "description": "Esta zapatilla presenta una parte superior fabricada con un hilo reciclado de alto rendimiento creado con al menos un 50% de Parley Ocean Plastic.",
        "price": 140,
        "stock": 12,
        "shoppingFrom": "España",
        "image": "https://assets.adidas.com/images/w_600,f_auto,q_auto/65462195082b4a8aaa6bad6b008b2da0_9366/Zapatilla_NMD_R1_V2_Blanco_GX6368.jpg",
        "rating": 4.5,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Adidas",
    },
    {
        "title": "Nike Air Zoom Pegasus 38",
        "description": "Sonríe con cada kilómetro.Las Pegasus 38 son un clásico de gran eficacia que ofrece una mayor comodidad y elasticidad para que disfrutes de tus carreras más largas.",
        "price": 124,
        "stock": 4,
        "shoppingFrom": "Francia",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c062b952-d202-4e33-8be2-7fc2c5e81beb/air-zoom-pegasus-38-zapatillas-de-running-carretera-bWMjP2.png",
        "rating": 5.0,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "Air Jordan 1 Hi FlyEase",
        "description": "Las Air Jordan 1 Hi FlyEase combinan el codiciado estilo de las primeras zapatillas exclusivas de Michael Jordan con un sistema de entrada rápido y sencillo con una sola mano.",
        "price": 159,
        "stock": 23,
        "shoppingFrom": "Alemania",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ef30042c-c7c1-40a4-896c-e9a4b0dd24e0/air-jordan-1-hi-flyease-zapatillas-F1Rw6B.png",
        "rating": 5.0,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "Nike Air Max 97 SE",
        "description": "Las Max Air cambiaron las reglas del juego en el 87. Ahora, celebramos su aniversario esmeralda (¡35 años!) con las Nike Air Max 97 SE. .",
        "price": 189.99,
        "stock": 12,
        "shoppingFrom": "Alemania",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/5ecc4749-74d4-4adb-9889-445c9dac4abd/air-max-97-se-zapatillas-FPxPtp.png",
        "rating": 4.1,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "ADIDAS Superstar",
        "description": "Diseño iconico para unas zapatillas hechas en piel en su parte exterior y con tela para un interior confortable.",
        "price": 49.95,
        "stock": 40,
        "shoppingFrom": "España",
        "image": "https://dakonda.com/57169-large_default/adidas-superstar-zapatillas.jpg",
        "rating": 3.9,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Adidas",
    },
    {
        "title": "ADIDAS Stan Smith",
        "description": "La zapatilla adidas Stan Smith lleva un buen tiempo dando de qué hablar. Para ser exactos, desde 1971.",
        "price": 100,
        "stock": 32,
        "shoppingFrom": "España",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c1f600512d8c4b1da89dad7c00f57ac8_9366/Zapatilla_Stan_Smith_Blanco_GW0486_01_standard.jpg",
        "rating": 4.2,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Adidas",
    },
    {
        "title": "Chuck Taylor All Star Leather",
        "description": "Están confeccionadas con un tejido de piel supersuave, y puedes hacer que sean tan elegantes o modernas como quieras. Tú escribes la historia.",
        "price": 80,
        "stock": 33,
        "shoppingFrom": "España",
        "image": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw6b9345d3/images/a_107/132173C_A_107X1.jpg?sw=2000",
        "rating": 4.9,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Converse",
    },
    {
        "title": "Vans Ward Suede",
        "description": "SUELA: Es la parte inferior de la zapatilla que toca el suelo.",
        "price": 38,
        "stock": 40,
        "shoppingFrom": "Francia",
        "image": "https://m.media-amazon.com/images/I/41MAOKcfhXL._AC_.jpg",
        "rating": 3.0,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Vans",
    },
    {
        "title": "Morrison Bel-Air",
        "description": "Las Morrison Nineties Bel-Air es un homenaje a la serie noventera “El Principe de Bel-Air”.",
        "price": 75,
        "stock": 20,
        "shoppingFrom": "España",
        "image": "https://morrisonshoes.com/1336-large_default/bel-air.jpg",
        "rating": 4.2,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Morrison",
    },
    {
        "title": "Veja Esplar",
        "description": "Algodón procedente de agricultura biológica. Cultivado sin pesticidas ni productos químicos.",
        "price": 99,
        "stock": 4,
        "shoppingFrom": "Francia",
        "image": "https://cdn.laredoute.com/products/f/8/d/f8d9733066ecdc25cbdd491482491977.jpg?imgopt=twic&twic=v1/cover=700x700",
        "rating": 3.0,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Veja",
    },
    {
        "title": "Puma Suede VTG GTX",
        "description": "Desde su llegada a escena en 1968, la colección Suede ha cambiado las reglas del juego y ha sido utilizada por figuras icónicas de varias generaciones. Y este modelo, diseñado...",
        "price": 99,
        "stock": 40,
        "shoppingFrom": "España",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/382790/01/sv01/fnd/EEA/fmt/png/Zapatillas-Suede-VTG-GTX",
        "rating": 4.0,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Puma",
    },
    {
        "title": "MUNICH ALPHA 65",
        "description": "Zapatillas deportivas de hombre Munich en blanco con detalles a contraste. ",
        "price": 100,
        "stock": 24,
        "shoppingFrom": "Alemania",
        "image": "https://dhb3yazwboecu.cloudfront.net/180/V5/FASHION/8410065-01-L.jpg",
        "rating": 3,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Munich",
    },
    {
        "title": "DC Trase",
        "description": "Parte superior: parte superior en ante, Tejido interior de malla, Logo HD estampado.",
        "price": 35,
        "stock": 4,
        "shoppingFrom": "Alemania",
        "image": "https://images.boardriders.com/globalGrey/dcshoes-products/all/default/xlarge/adys300652_dcshoes,p_2gg_frt2.jpg",
        "rating": 3,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "DC",
    },
    {
        "title": "Nike Air Zoom SuperRep 3",
        "description": "Libera toda tu potencia en cada repetición con unas zapatillas rediseñadas que aportan sujeción y estabilidad a cada movimiento.",
        "price": 130,
        "stock": 32,
        "shoppingFrom": "Alemania",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/8f15f60f-151f-4e0f-8625-d28491814cb6/air-zoom-superrep-3-zapatillas-las-clases-de-hiit-bjJmZ8.png",
        "rating": 4,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "Nike Air Max 90 Premium",
        "description": "No hay nada tan cómodo.No hay nada tan demostrado.Las Nike Air Max 90 Premium se mantienen fieles a sus raíces con la icónica suela tipo gofre.",
        "price": 160,
        "stock": 40,
        "shoppingFrom": "Alemania",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/f3a5907b-fc05-49ee-8d20-9855b5d8b216/air-max-90-zapatillas-Z8GT9f.png",
        "rating": 4.2,
        "categorie": "Sneakers",
        "subcategorie":"Man",
        "filter": "Nike",
    },
    {
        "title": "Nike Air Force 1 Pixel",
        "description": "Siempre has dado en el clavo. Por lo que las Nike Air Force 1 Pixel son perfectas para ti.",
        "price": 112,
        "stock": 4,
        "shoppingFrom": "Alemania",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/a2ba5c4d-2746-42e6-a42f-677c6bcefba7/air-force-1-pixel-zapatillas-4Hcq7k.png",
        "rating": 5,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
    },
//Hasta aqui bien



{
        "title": "Nike Blazer Low Platform",
        "description": "Alabadas por su simplicidad y comodidad clásicas, las Nike Blazer Low Platform elevan este icono del baloncesto.",
        "price": 94.99,
        "stock": 24 ,
        "shoppingFrom": "Frncia",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/de9ab74a-c988-448b-b29b-dd1a70ebfb40/blazer-low-platform-zapatillas-vgnjcQ.png",
        "rating":4 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
    },
{
        "title": "Nike Air Force 1 '07 Low",
        "description": "Las Nike Air Force 1 '07 Low se actualizan con detalles artesanales.",
        "price": 129.9 ,
        "stock": 15 ,
        "shoppingFrom": "Alemania",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/0df72176-9957-4592-b2f4-740194135c93/air-force-1-07-low-zapatillas-T7R7Qw.png",
        "rating":5 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
        }
    ,
{
        "title": "Nike Air Max Dawn",
        "description": "Las Air Max Dawn se mantienen fieles a sus orígenes y están confeccionadas con al menos un 20 % de material reciclado por peso.",
        "price": 114.99 ,
        "stock": 23,
        "shoppingFrom": "Francia",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/aa654de9-05f0-4708-bfdd-c4fb028e540a/air-max-dawn-zapatillas-r4f7lJ.png",
        "rating": 4.5 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
    },
{
        "title": "Nike Air Huarache",
        "description": "¿Cómo mejorar este clásico del baloncesto de los 90? Los revestimientos de estilo caparazón de tortuga y el clip tonal del talón son increíbles innovaciones de estilo.",
        "price": 129.99,
        "stock": 0,
        "shoppingFrom": "Italia",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/d05e764f-7040-432d-bae9-1a01d6bc768d/air-huarache-zapatillas-rrDPq6.png",
        "rating": 5,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
    },
    //Hasta aqui bien
{
        "title": "Nike Air Max Pre-Day",
        "description": "Lleva el look de las zapatillas de running Nike tradicionales a una nueva dimensión.",
        "stock": 12,
        "shoppingFrom": "España",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/fcac342d-db2f-4409-a5bd-89955d756f7e/air-max-pre-day-zapatillas-bz0VKf.png",
        "rating": 5 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "price": 59,
        "filter": "Nike",
    },
{
        "title": "Air Force 1 '07",
        "description": "El fulgor sigue vivo con las Nike Air Force 1 '07, un icono del baloncesto que aporta un nuevo toque.",
        "price": 129.99 ,
        "stock": 23 ,
        "shoppingFrom": "Alemania",
        "image": " https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/7d5a4747-8d00-41e3-a953-92dad756cb17/air-force-1-07-zapatillas-L8NbRw.png ",
        "rating": 5 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
    },
{
        "title": "Nike Air Max 2021",
        "description": "Podríamos afirmar que el innovador sistema Air ofrece la mejor sensación hasta el momento.",
        "price": 160 ,
        "stock": 1 ,
        "shoppingFrom": "Italia",
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/bca654a7-fe86-408e-91d9-31b88092067e/air-max-2021-zapatillas-2hZTzG.png",
        "rating":4 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Nike",
    },
{
        "title": "ADIDAS ZX 10000 DISNEY",
        "description": "Adorabilidad y orgullo no es un binomio imposible. Esta zapatilla adidas es la prueba definitiva.",
        "price": 130,
        "stock": 23 ,
        "shoppingFrom": " España",
        "image": "https://assets.adidas.com/images/w_600,f_auto,q_auto/047139c7d4eb46e69312adce010d42e2_9366/Zapatilla_ZX_10000_Disney_Negro_GW8312.jpg ",
        "rating": 3 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Adidas",
    },
{
        "title": "ADIDAS OZRAH",
        "description": "¿Quieres comodidad sin renunciar a un look rompedor? Con esta zapatilla adidas Ozrah puedes tenerlo todo. ",
        "price":140 ,
        "stock":3 ,
        "shoppingFrom": "España",
        "image": "https://assets.adidas.com/images/w_600,f_auto,q_auto/6690d41645ad4549b56fad740115fa5f_9366/Zapatilla_Ozrah_Rosa_GW5619.jpg",
        "rating": 5 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Adidas",
    },
{
        "title": "ADIDAS HER COURT",
        "description": "Ligera y elegante. Así es la zapatilla Her Court de adidas. La parte superior de piel de color naranja lo corrobora. ",
        "price":110 ,
        "stock": 30,
        "shoppingFrom": " España ",
        "image": "https://assets.adidas.com/images/w_600,f_auto,q_auto/448623076e66481f9bc5adf001587051_9366/Zapatilla_Her_Court_Naranja_GY3581.jpg",
        "rating": 4 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Adidas",
    },
{
        "title": "ADIDAS NIZZA TREK DISNEY",
        "description": "Impúlsate con la energía de Bambi. Ponte esta zapatilla adidas y rinde homenaje al famoso cervatillo y a la primera ilustradora que apareció en los créditos de una peli de Disney. ",
        "price": 100 ,
        "stock": 20,
        "shoppingFrom": "Italia",
        "image": "https://assets.adidas.com/images/w_600,f_auto,q_auto/b993d7704f944834a031ade5010f8a6b_9366/Zapatilla_Nizza_Trek_Disney_Blanco_GZ1654.jpg ",
        "rating": 4 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Adidas",
    },
{
        "title": "Chuck Taylor All Star Move Platform Seasonal Color",
        "description": "Los colores más inclusivos transforman el look gracias a los tonos primaverales reinventados.",
        "price":  90,
        "stock": 40 ,
        "shoppingFrom": "Alemania",
        "image": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw553b7f7c/images/d_08/572722C_D_08X1.jpg?sw=406",
        "rating": 4 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Converse",
    },
{
        "title": "Chuck 70 Embroidered Lips",
        "description": "El bordado 'Love me' (Quiéreme) y los besos estampados aportan un toque especial a las Chuck 70 premium.",
        "price": 95,
        "stock": 10 ,
        "shoppingFrom": "España",
        "image": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw7c458f41/images/d_08/A01601C_D_08X1.jpg?sw=406 ",
        "rating": 5 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Converse",
    },
{
        "title": "Chuck Taylor All Star Lift Platform Faux Flower Petals",
        "description": "Regálate flores que no se marchitarán con las Chuck de plataforma inspiradas en los pétalos.",
        "price": 140 ,
        "stock": 23 ,
        "shoppingFrom": "España ",
        "image": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw9d644293/images/d_08/A02107C_D_08X1.jpg?sw=406",
        "rating": 2 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Converse",
    },
{
        "title": "Run Star Motion Platform",
        "description": "Los detalles atrevidos y exagerados de la mediasuela le dan un estilo irresistible a tus plataformas favoritas.",
        "price": 110,
        "stock": 4 ,
        "shoppingFrom": " Italia ",
        "image": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwfc052ec0/images/d_08/172896C_D_08X1.jpg?sw=406",
        "rating": 4 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Converse",
    },
{
        "title": "Run Star Motion",
        "description": "Nuevas líneas atrevidas y comodidad CX a otro nivel.",
        "price": 120 ,
        "stock":  5 ,
        "shoppingFrom": " Italia ",
        "image": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw44086128/images/d_08/171545C_D_08X1.jpg?sw=406",
        "rating": 3 ,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Converse",
    },
{
        "title": "Chuck Taylor All Star Move Platform Ombre",
        "description": "El toque degradado aporta un estilo innovador a este modelo con plataforma ultraligera",
        "price": 95 ,
        "stock": 33 ,
        "shoppingFrom": " España ",
        "image": " https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwbb956e65/images/d_08/572898C_D_08X1.jpg?sw=406 ",
        "rating": 4,
        "categorie": "Sneakers",
        "subcategorie":"Woman",
        "filter": "Converse",
    }
]

const URL = "mongodb://localhost:27017/ecomerce";

mongoose.connect(URL, CONFIG_DB)
.then(async () =>{
    const sneakersProductsContent = await SneakersModel.find();
    (sneakersProductsContent) ? await SneakersModel.collection.drop() : '';
})
.catch(error =>console.log('Error buscando en la DB'))
.then(async () =>{
    await SneakersModel.insertMany(sneakersProductsArray);
})
.catch(error =>console.log('Error añadiendo las nuevas zapatillas'))
.finally(() => mongoose.disconnect());
